services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=conference'
      - 'POSTGRES_PASSWORD=megastar'
      - 'POSTGRES_USER=tallink'
    ports:
      - '5432:5432'
